version: '3.8'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8098:80
        links:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www
        links:
            - frontend
    frontend:
        build:
            context: .
            dockerfile: docker/Node.Dockerfile
        volumes:
            - ./:/var/www
        links:
            - mysql
    mysql:
        build:
            context: .
            dockerfile: docker/Mysql.Dockerfile
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=website


