version: '3.8'

services:
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www
        links:
            - nginx
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - 8098:80
